### PR TITLE
 Run: npm audit fix

### PR DESCRIPTION
**Pull request by michaeljmarshall**
When running `npm install`, the project currently outputs the following warning:

```
found 1538 vulnerabilities (663 low, 203 moderate, 672 high)
```

It recommends running `npm audit fix`. These changes are the result of running that command.

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
Looks like I needed to also run `npm install` after running the initial fix command. Added that change in a new commit. Also, `npm install` now logs the following warning about vulnerabilities:

```
found 188 vulnerabilities (167 low, 12 moderate, 9 high)
```

We'll need to address those remaining vulnerabilities too.

**Comment by michaeljmarshall** [comment]
With the downgrade of bootstrap back to 4.0.0, the current vulnerability listing is as follows:
```
found 189 vulnerabilities (167 low, 13 moderate, 9 high)
```

**Comment by cdbartholomew** [comment]
Should we run `npm audit fix` as part of the Docker build?

**Review by lhotari — APPROVED** [review]

**Comment by lhotari** [comment]
@michaeljmarshall did you also run `npm audit fix` for the server component?

**Comment by michaeljmarshall** [comment]
> Should we run `npm audit fix` as part of the Docker build?

@cdbartholomew - I don't think we should do that, as that could mean the dependencies in the docker image might not match the `package-lock.json` in this repo. Perhaps we should fail the build if too `npm audit` results in any high priority vulnerabilites?

> @michaeljmarshall did you also run `npm audit fix` for the server component?

@lhotari - good catch, I didn't notice that portion of code. I'll merge this and follow up with another commit.

**Pull request merged**
